spring.datasource.url=jdbc:postgresql://localhost:5432/database_dummy
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=api
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.h2.console.enabled=false
spring.jpa.show-sql=false
spring.jackson.deserialization.accept-empty-string-as-null-object=true